apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: artifactcache
      app.kubernetes.io/component: service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: artifactcache
        app.kubernetes.io/component: service
    spec:
      containers:
        - name: artifactcache
          image: inloco/artifactcache
          envFrom:
            - configMapRef:
                name: service
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          resources:
            requests:
              cpu: 125m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 2048Mi
      securityContext:
        fsGroup: 65532
      serviceAccountName: service
